"use client";

import { useMutation } from "@tanstack/react-query";
import { ArrowUp, Sparkles } from "lucide-react";
import { type FormEvent, useCallback, useEffect, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import { api } from "@/lib/api";
import { cn } from "@/lib/utils";
import type { AIMessage } from "@/lib/types";

const SYSTEM_PROMPT =
  "You are a revenue analyst for a B2B SaaS company. You have access to Stripe data (customers, subscriptions, charges). Answer concisely. When you cite a specific customer or transaction, prefix the reference with `cite:` so the UI can format it.";

const SUGGESTIONS = [
  "Which customers churned last month?",
  "Why did MRR change this week?",
  "Top 5 revenue contributors over the last quarter",
];

export default function AiAssistantPage() {
  const [messages, setMessages] = useState<AIMessage[]>([]);
  const [draft, setDraft] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);

  const sendMessage = useMutation({
    mutationFn: (next: AIMessage[]) =>
      api.aiMessage(
        next.map((m) => ({ role: m.role, content: m.content })),
        SYSTEM_PROMPT
      ),
    onSuccess: (resp) => {
      setMessages((prev) => [...prev, { role: "assistant", content: resp.text }]);
    },
  });

  const send = useCallback(
    (text: string) => {
      const trimmed = text.trim();
      if (!trimmed || sendMessage.isPending) return;
      const next: AIMessage[] = [...messages, { role: "user", content: trimmed }];
      setMessages(next);
      setDraft("");
      sendMessage.mutate(next);
    },
    [messages, sendMessage]
  );

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, sendMessage.isPending]);

  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    send(draft);
  };

  return (
    <div className="flex h-screen flex-col">
      <header className="border-b border-line px-10 py-6">
        <h1 className="font-heading text-2xl font-semibold tracking-tight text-ink">
          AI Assistant
        </h1>
        <p className="mt-1 text-sm text-fade">
          Ask anything about your revenue data. Answers are generated by Claude.
        </p>
      </header>

      <div ref={scrollRef} className="flex-1 overflow-y-auto px-10 py-8">
        <div className="mx-auto max-w-3xl space-y-6">
          {messages.length === 0 && !sendMessage.isPending && (
            <EmptyState onPick={send} />
          )}
          {messages.map((m, i) => (
            <MessageBubble key={i} message={m} />
          ))}
          {sendMessage.isPending && (
            <div className="flex items-center gap-2 text-sm text-fade">
              <Sparkles className="h-4 w-4 animate-pulse text-accent" />
              <span className="font-heading">thinking…</span>
            </div>
          )}
          {sendMessage.isError && (
            <div className="rounded-md border border-line bg-elev px-4 py-3 text-sm text-mute">
              {(sendMessage.error as Error).message}
            </div>
          )}
        </div>
      </div>

      <form onSubmit={onSubmit} className="border-t border-line bg-panel px-10 py-5">
        <div className="mx-auto flex max-w-3xl items-end gap-3">
          <textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                send(draft);
              }
            }}
            placeholder="Ask about your revenue, customers, or trends…"
            rows={1}
            className={cn(
              "min-h-[44px] flex-1 resize-none rounded-md border border-line bg-base px-3 py-2.5 text-sm text-ink",
              "placeholder:text-fade focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
            )}
          />
          <Button type="submit" size="icon" disabled={!draft.trim() || sendMessage.isPending}>
            <ArrowUp className="h-4 w-4" />
          </Button>
        </div>
      </form>
    </div>
  );
}

function MessageBubble({ message }: { message: AIMessage }) {
  const isUser = message.role === "user";
  return (
    <div className={cn("flex gap-4", isUser ? "justify-end" : "justify-start")}>
      {!isUser && (
        <div className="mt-1 flex h-7 w-7 flex-none items-center justify-center rounded-md bg-line text-accent">
          <Sparkles className="h-3.5 w-3.5" />
        </div>
      )}
      <div
        className={cn(
          "max-w-[80%] rounded-lg px-4 py-3 text-sm leading-relaxed",
          isUser ? "bg-line text-ink" : "border border-line bg-panel text-mute"
        )}
      >
        {message.content}
      </div>
    </div>
  );
}

function EmptyState({ onPick }: { onPick: (text: string) => void }) {
  return (
    <div className="rounded-lg border border-line bg-panel p-10">
      <div className="flex items-center gap-3">
        <Sparkles className="h-5 w-5 text-accent" />
        <div className="font-heading text-base font-semibold text-ink">Try asking…</div>
      </div>
      <p className="mt-1 text-sm text-fade">
        Pick a starter question or type your own below.
      </p>
      <div className="mt-6 grid gap-2">
        {SUGGESTIONS.map((s) => (
          <button
            key={s}
            type="button"
            onClick={() => onPick(s)}
            className="rounded-md border border-line bg-base px-4 py-3 text-left text-sm text-ink transition-colors hover:border-accent/40"
          >
            {s}
          </button>
        ))}
      </div>
    </div>
  );
}
