"""add stripe data tables (customers, subscriptions, charges, sync_logs)

Revision ID: 3b21ec07a6e7
Revises: 03a4bfe8a0f2
Create Date: 2026-05-16 16:55:13.214867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b21ec07a6e7'
down_revision: Union[str, None] = '03a4bfe8a0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('stripe_charge_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('amount_refunded', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('refunded', sa.Boolean(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('stripe_metadata', sa.JSON(), nullable=True),
    sa.Column('stripe_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['platform_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'stripe_charge_id', name='uq_connection_charge')
    )
    op.create_index(op.f('ix_stripe_charges_connection_id'), 'stripe_charges', ['connection_id'], unique=False)
    op.create_index(op.f('ix_stripe_charges_id'), 'stripe_charges', ['id'], unique=False)
    op.create_index(op.f('ix_stripe_charges_status'), 'stripe_charges', ['status'], unique=False)
    op.create_index(op.f('ix_stripe_charges_stripe_charge_id'), 'stripe_charges', ['stripe_charge_id'], unique=False)
    op.create_index(op.f('ix_stripe_charges_stripe_created_at'), 'stripe_charges', ['stripe_created_at'], unique=False)
    op.create_index(op.f('ix_stripe_charges_stripe_customer_id'), 'stripe_charges', ['stripe_customer_id'], unique=False)
    op.create_table('stripe_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('delinquent', sa.Boolean(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('stripe_metadata', sa.JSON(), nullable=True),
    sa.Column('stripe_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['platform_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'stripe_customer_id', name='uq_connection_customer')
    )
    op.create_index(op.f('ix_stripe_customers_connection_id'), 'stripe_customers', ['connection_id'], unique=False)
    op.create_index(op.f('ix_stripe_customers_id'), 'stripe_customers', ['id'], unique=False)
    op.create_index(op.f('ix_stripe_customers_stripe_customer_id'), 'stripe_customers', ['stripe_customer_id'], unique=False)
    op.create_table('stripe_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('amount_per_period', sa.BigInteger(), nullable=False),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_json', sa.JSON(), nullable=True),
    sa.Column('stripe_metadata', sa.JSON(), nullable=True),
    sa.Column('stripe_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['platform_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'stripe_subscription_id', name='uq_connection_subscription')
    )
    op.create_index(op.f('ix_stripe_subscriptions_connection_id'), 'stripe_subscriptions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_id'), 'stripe_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_status'), 'stripe_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_stripe_created_at'), 'stripe_subscriptions', ['stripe_created_at'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_stripe_customer_id'), 'stripe_subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_stripe_subscription_id'), 'stripe_subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['platform_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_connection_id'), 'sync_logs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_sync_logs_id'), 'sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_logs_status'), 'sync_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_logs_status'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_connection_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_stripe_subscriptions_stripe_subscription_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_stripe_customer_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_stripe_created_at'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_status'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_connection_id'), table_name='stripe_subscriptions')
    op.drop_table('stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_customers_stripe_customer_id'), table_name='stripe_customers')
    op.drop_index(op.f('ix_stripe_customers_id'), table_name='stripe_customers')
    op.drop_index(op.f('ix_stripe_customers_connection_id'), table_name='stripe_customers')
    op.drop_table('stripe_customers')
    op.drop_index(op.f('ix_stripe_charges_stripe_customer_id'), table_name='stripe_charges')
    op.drop_index(op.f('ix_stripe_charges_stripe_created_at'), table_name='stripe_charges')
    op.drop_index(op.f('ix_stripe_charges_stripe_charge_id'), table_name='stripe_charges')
    op.drop_index(op.f('ix_stripe_charges_status'), table_name='stripe_charges')
    op.drop_index(op.f('ix_stripe_charges_id'), table_name='stripe_charges')
    op.drop_index(op.f('ix_stripe_charges_connection_id'), table_name='stripe_charges')
    op.drop_table('stripe_charges')
    # ### end Alembic commands ###
