"""add ai_reviews

Revision ID: e0af0e51d9e6
Revises: 3b21ec07a6e7
Create Date: 2026-05-17 11:30:17.106424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0af0e51d9e6'
down_revision: Union[str, None] = '3b21ec07a6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reviews_created_at'), 'ai_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_reviews_id'), 'ai_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_ai_reviews_organization_id'), 'ai_reviews', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_reviews_period_end'), 'ai_reviews', ['period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_reviews_period_end'), table_name='ai_reviews')
    op.drop_index(op.f('ix_ai_reviews_organization_id'), table_name='ai_reviews')
    op.drop_index(op.f('ix_ai_reviews_id'), table_name='ai_reviews')
    op.drop_index(op.f('ix_ai_reviews_created_at'), table_name='ai_reviews')
    op.drop_table('ai_reviews')
    # ### end Alembic commands ###
